#![allow(clippy::cast_possible_truncation, reason = "needs triage")]
#![allow(clippy::undocumented_unsafe_blocks, reason = "TODO")]

use core::fmt;

use rand_core::{Infallible, SeedableRng, TryCryptoRng, TryRng};

#[cfg(feature = "zeroize")]
use zeroize::{Zeroize, ZeroizeOnDrop};

use crate::{
    ChaChaCore, R8, R12, R20, Rounds, backends,
    variants::{Legacy, Variant},
};

use cfg_if::cfg_if;

/// Seed value used to initialize ChaCha-based RNGs.
pub type Seed = [u8; 32];

/// Serialized RNG state.
pub type SerializedRngState = [u8; 49];

/// Number of 32-bit words per ChaCha block (fixed by algorithm definition).
pub(crate) const BLOCK_WORDS: u8 = 16;

/// Number of blocks generated by RNG core.
const BUF_BLOCKS: u8 = 4;
/// Buffer size in words used by buffered RNG.
const BUFFER_SIZE: usize = (BLOCK_WORDS * BUF_BLOCKS) as usize;

impl<R: Rounds, V: Variant> SeedableRng for ChaChaCore<R, V> {
    type Seed = Seed;

    #[inline]
    fn from_seed(seed: Self::Seed) -> Self {
        ChaChaCore::new_internal(&seed, &[0u8; 8])
    }
}

impl<R: Rounds, V: Variant> ChaChaCore<R, V> {
    /// Constructs a ChaChaCore from a pointer to a seed.
    #[inline]
    pub unsafe fn seed_from_ptr(ptr: *const u8) -> Self {
        let arr = ptr.cast_array::<32>();
        let arr = unsafe { *arr };
        ChaChaCore::new_internal(&arr, &[0u8; 8])
    }
}

trait Observable: Copy {
    type Bytes: Sized + AsRef<[u8]>;
    fn to_le_bytes(self) -> Self::Bytes;
}
impl Observable for u32 {
    type Bytes = [u8; 4];

    fn to_le_bytes(self) -> Self::Bytes {
        Self::to_le_bytes(self)
    }
}

fn fill_via_chunks<T: Observable>(src: &[T], dest: &mut [u8]) -> (usize, usize) {
    let size = size_of::<T>();

    // Always use little endian for portability of results.

    let mut dest = dest.chunks_exact_mut(size);
    let mut src = src.iter();

    let zipped = dest.by_ref().zip(src.by_ref());
    let num_chunks = zipped.len();
    zipped.for_each(|(dest, src)| dest.copy_from_slice(src.to_le_bytes().as_ref()));

    let byte_len = num_chunks * size;
    if let (dest_tail @ [_, ..], Some(src)) = (dest.into_remainder(), src.next()) {
        let n = dest_tail.len();
        dest_tail.copy_from_slice(&src.to_le_bytes().as_ref()[..n]);
        (num_chunks + 1, byte_len + n)
    } else {
        (num_chunks, byte_len)
    }
}

impl<R: Rounds, V: Variant> ChaChaCore<R, V> {
    fn generate(&mut self, dest_ptr: *mut u8, num_bytes: usize, buffer: &mut [u32; BUFFER_SIZE]) {
        let fill_buffer = num_bytes % (BUFFER_SIZE * 4) != 0;
        cfg_if! {
            if #[cfg(chacha20_backend = "soft")] {
                backends::soft::Backend(self).gen_ks_blocks(dest_ptr, num_bytes, fill_buffer, buffer);
            } else if #[cfg(any(target_arch = "x86", target_arch = "x86_64"))] {
                cfg_if! {
                    // AVX-512 doesn't support RNG, so use AVX-2 instead
                    if #[cfg(any(chacha20_backend = "avx2", chacha20_backend = "avx512"))] {
                        unsafe {
                            backends::avx2::rng_inner::<R, V>(self, dest_ptr, num_bytes, fill_buffer, buffer);
                        }
                    } else if #[cfg(chacha20_backend = "sse2")] {
                        unsafe {
                            backends::sse2::rng_inner::<R, V>(self, dest_ptr, num_bytes, fill_buffer, buffer);
                        }
                    } else {
                        #[cfg(chacha20_avx512)]
                        let (_avx512_token, avx2_token, sse2_token) = self.tokens;
                        #[cfg(not(chacha20_avx512))]
                        let (avx2_token, sse2_token) = self.tokens;

                        if avx2_token.get() {
                            unsafe {
                                backends::avx2::rng_inner::<R, V>(self, dest_ptr, num_bytes, fill_buffer, buffer);
                            }
                        } else if sse2_token.get() {
                            unsafe {
                                backends::sse2::rng_inner::<R, V>(self, dest_ptr, num_bytes, fill_buffer, buffer);
                            }
                        } else {
                            backends::soft::Backend(self).gen_ks_blocks(dest_ptr, num_bytes, fill_buffer, buffer);
                        }
                    }
                }
            } else if #[cfg(all(target_arch = "aarch64", target_feature = "neon"))] {
                // SAFETY: we have used conditional compilation to ensure NEON is available
                unsafe {
                    backends::neon::rng_inner::<R, V>(self, dest_ptr, num_bytes, fill_buffer, buffer);
                }
            } else {
                backends::soft::Backend(self).gen_ks_blocks(dest_ptr, num_bytes, fill_buffer, buffer);
            }
        }
    }
}

macro_rules! impl_chacha_rng {
    ($Rng:ident, $rounds:ident) => {
        /// A cryptographically secure random number generator that uses the ChaCha stream cipher.
        ///
        /// See the [crate docs][crate] for more information about the underlying stream cipher.
        ///
        /// This RNG implementation uses a 64-bit counter and 64-bit stream identifier (a.k.a nonce).
        /// A 64-bit counter over 64-byte (16 word) blocks allows 1 ZiB of output before cycling,
        /// and the stream identifier allows 2<sup>64</sup> unique streams of output per seed.
        /// Both counter and stream are initialized to zero but may be set via the [`set_word_pos`]
        /// and [`set_stream`] methods.
        ///
        /// [`set_word_pos`]: Self::set_word_pos
        /// [`set_stream`]: Self::set_stream
        ///
        /// # Example
        ///
        /// ```rust
        #[doc = concat!("use chacha20::", stringify!($Rng), ";")]
        /// use rand_core::{SeedableRng, Rng};
        ///
        /// let seed = [42u8; 32];
        #[doc = concat!("let mut rng = ", stringify!($Rng), "::from_seed(seed);")]
        ///
        /// let random_u32 = rng.next_u32();
        /// let random_u64 = rng.next_u64();
        ///
        /// let mut random_bytes = [0u8; 3];
        /// rng.fill_bytes(&mut random_bytes);
        /// ```
        ///
        /// See the [`rand`](https://docs.rs/rand/) crate for more advanced RNG functionality.
        pub struct $Rng {
            core: ChaChaCore<$rounds, Legacy>,
            buffer: [u32; BUFFER_SIZE],
        }

        impl SeedableRng for $Rng {
            type Seed = Seed;

            #[inline]
            fn from_seed(seed: Self::Seed) -> Self {
                let core = ChaChaCore::new_internal(&seed, &[0u8; 8]);
                let mut rng = Self {
                    core,
                    buffer: [0u32; BUFFER_SIZE],
                };
                rng.buffer[0] = BUFFER_SIZE as u32;
                rng
            }
        }

        #[cfg(feature = "zeroize")]
        impl Drop for $Rng {
            fn drop(&mut self) {
                self.buffer.zeroize();
            }
        }

        impl TryRng for $Rng {
            type Error = Infallible;

            #[inline]
            fn try_next_u32(&mut self) -> Result<u32, Self::Error> {
                let mut index = self.index();
                if index >= BUFFER_SIZE {
                    self.core.generate(
                        self.buffer.as_mut_ptr() as *mut u8,
                        BUFFER_SIZE * 4,
                        &mut self.buffer,
                    );
                    index = 0;
                }
                let value = self.buffer[index];
                *self.index_mut() = index as u32 + 1;
                Ok(value)
            }
            #[inline]
            fn try_next_u64(&mut self) -> Result<u64, Self::Error> {
                let mut new_index: u32;
                let (mut lo, mut hi);
                let index = self.index();
                if index < BUFFER_SIZE - 1 {
                    lo = self.buffer[index];
                    hi = self.buffer[index + 1];
                    new_index = index as u32 + 2;
                } else {
                    lo = self.buffer[BUFFER_SIZE - 1];
                    self.core.generate(
                        self.buffer.as_mut_ptr() as *mut u8,
                        BUFFER_SIZE * 4,
                        &mut self.buffer,
                    );
                    hi = self.buffer[0];
                    new_index = 1;
                    if index >= BUFFER_SIZE {
                        lo = hi;
                        hi = self.buffer[1];
                        new_index = 2;
                    }
                }
                *self.index_mut() = new_index;
                Ok((u64::from(hi) << 32) | u64::from(lo))
            }
            #[inline]
            fn try_fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), Self::Error> {
                let dest_len = dest.len();
                let index = self.index();
                let remaining = ((BUFFER_SIZE * 4) - (index * 4)).min(dest_len);

                let mut dest_pos = 0;

                if remaining != 0 && index < BUFFER_SIZE && index != 0 {
                    let (consumed_u32, filled_u8) =
                        fill_via_chunks(&self.buffer.as_ref()[index..], &mut dest[0..]);
                    *self.index_mut() += consumed_u32 as u32;
                    debug_assert!(index <= BUFFER_SIZE);
                    dest_pos += filled_u8;

                    if dest_len == dest_pos {
                        return Ok(());
                    }
                }

                let remaining = dest_len - dest_pos;
                unsafe {
                    let chunk_ptr = dest.as_mut_ptr().add(dest_pos);
                    self.core
                        .generate(chunk_ptr as *mut u8, remaining, &mut self.buffer);
                }
                let parblocks = remaining / 256;
                dest_pos += parblocks * 256;
                if dest_pos == dest_len {
                    return Ok(());
                }

                let (consumed_u32, _filled_u8) =
                    fill_via_chunks(&self.buffer.as_ref()[0..], &mut dest[dest_pos..]);
                *self.index_mut() = consumed_u32 as u32;
                Ok(())
            }
        }

        impl TryCryptoRng for $Rng {}

        #[cfg(feature = "zeroize")]
        impl ZeroizeOnDrop for $Rng {}

        // We use custom implementation of `PartialEq` because RNG states
        // may buffer different parts of the same keystream, while keeping
        // buffer cursor pointing towards the same keystream point.
        impl PartialEq<$Rng> for $Rng {
            fn eq(&self, rhs: &$Rng) -> bool {
                (self.get_seed() == rhs.get_seed())
                    && (self.get_stream() == rhs.get_stream())
                    && (self.get_word_pos() == rhs.get_word_pos())
            }
        }

        impl Eq for $Rng {}

        // Custom Debug implementation that does not expose the internal state
        impl fmt::Debug for $Rng {
            fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                write!(f, concat!(stringify!($Rng), " {{ ... }}"))
            }
        }

        impl $Rng {
            /// Initializes an RNG with a pointer
            #[inline]
            pub fn seed_from_ptr(seed: *const u8) -> Self {
                let core = unsafe { ChaChaCore::seed_from_ptr(seed) };
                let mut rng = Self {
                    core,
                    buffer: [0u32; BUFFER_SIZE],
                };
                rng.buffer[0] = BUFFER_SIZE as u32;
                rng
            }
            /// Get the offset from the start of the stream, in 32-bit words.
            ///
            /// Since the generated blocks are 64 words (2<sup>6</sup>) long and the
            /// counter is 64-bits, the offset is a 68-bit number. Sub-word offsets are
            /// not supported, hence the result can simply be multiplied by 4 to get a
            /// byte-offset.
            #[inline]
            #[must_use]
            pub fn get_word_pos(&self) -> u128 {
                let index = self.index() % BUFFER_SIZE;
                let mut block_counter =
                    (u64::from(self.core.state[13]) << 32) | u64::from(self.core.state[12]);
                if index != 0 {
                    block_counter = block_counter.wrapping_sub(u64::from(BUF_BLOCKS));
                }
                let word_pos = u128::from(block_counter) * u128::from(BLOCK_WORDS) + index as u128;
                // eliminate bits above the 68th bit
                word_pos & ((1 << 68) - 1)
            }

            /// Gets a mutable reference to the RNG's index.
            #[inline(always)]
            fn index_mut(&mut self) -> &mut u32 {
                &mut self.buffer[0]
            }

            /// Gets the index as a `usize`.
            #[inline(always)]
            fn index(&self) -> usize {
                self.buffer[0] as usize
            }

            /// Resets the RNG with a specified index.
            #[inline(always)]
            fn reset(&mut self, mut index: usize) {
                if index == 0 || index == BUFFER_SIZE {
                    *self.index_mut() = BUFFER_SIZE as u32;
                    return;
                }
                self.core.generate(
                    self.buffer.as_mut_ptr() as *mut u8,
                    BUFFER_SIZE * 4,
                    &mut self.buffer,
                );
                *self.index_mut() = index as u32;
            }

            /// Set the offset from the start of the stream, in 32-bit words.
            ///
            /// **This value will be erased when calling `set_stream()`,
            /// so call `set_stream()` before calling `set_word_pos()`**
            /// if you intend on using both of them together.
            ///
            /// As with `get_word_pos`, we use a 68-bit number. Since the generator
            /// simply cycles at the end of its period (1 ZiB), we ignore the upper
            /// 60 bits.
            #[inline]
            pub fn set_word_pos(&mut self, word_offset: u128) {
                let index = (word_offset % u128::from(BLOCK_WORDS)) as usize;
                let counter = word_offset / u128::from(BLOCK_WORDS);
                //self.set_block_pos(counter as u64);
                self.core.state[12] = counter as u32;
                self.core.state[13] = (counter >> 32) as u32;
                self.reset(index);
            }

            /// Sets the block pos and resets the RNG's index.
            ///
            /// **This value will be erased when calling `set_stream()`,
            /// so call `set_stream()` before calling `set_block_pos()`**
            /// if you intend on using both of them together.
            ///
            /// The word pos will be equal to `block_pos * 16 words per block`.
            #[inline]
            #[allow(unused)]
            pub fn set_block_pos(&mut self, block_pos: u64) {
                self.reset(0);
                self.core.set_block_pos(block_pos);
            }

            /// Get the block pos.
            #[inline]
            #[allow(unused)]
            #[must_use]
            pub fn get_block_pos(&self) -> u64 {
                let counter = self.core.get_block_pos();
                let offset = self.index() % 64;
                if offset != 0 {
                    counter - u64::from(BUF_BLOCKS) + offset as u64 / 16
                } else {
                    counter
                }
            }

            /// Set the stream ID and reset the `word_pos` to 0.
            #[inline]
            pub fn set_stream(&mut self, stream: u64) {
                self.core.state[14] = stream as u32;
                self.core.state[15] = (stream >> 32) as u32;
                self.set_block_pos(0);
            }

            /// Get the stream number (nonce).
            #[inline]
            #[must_use]
            pub fn get_stream(&self) -> u64 {
                let mut result = [0u8; 8];
                result[..4].copy_from_slice(&self.core.state[14].to_le_bytes());
                result[4..].copy_from_slice(&self.core.state[15].to_le_bytes());
                u64::from_le_bytes(result)
            }

            /// Get the RNG seed.
            #[inline]
            #[must_use]
            pub fn get_seed(&self) -> [u8; 32] {
                let seed = &self.core.state[4..12];
                let mut result = [0u8; 32];
                for (src, dst) in seed.iter().zip(result.chunks_exact_mut(4)) {
                    dst.copy_from_slice(&src.to_le_bytes())
                }
                result
            }

            /// Sets the last row of the state using a pointer so that any type
            /// of data can be used, and it sets all words of the last row in
            /// one method call, as opposed to 2.
            ///
            /// # Safety
            ///
            /// * **Alignment**: The `data` pointer must be aligned to at least a 4-byte boundary.
            /// * **Initialization**: The memory pointed to by `data` must be fully initialized for 16 bytes.
            /// * **Layout**: The caller must ensure the source data has no internal padding.
            ///   If using a struct as the source, it must be `#[repr(C, packed(4))]` or `#[repr(C)]`
            ///   with fields that total exactly 128 bits without padding.
            ///
            /// # Example
            /// ```rust
            /// use chacha20::{ChaCha8Rng, rand_core::SeedableRng};
            /// #[repr(C, packed(4))]
            /// struct LastRow {
            ///     a: u32,
            ///     b: u64,
            ///     c: u32,
            /// }
            ///
            /// impl LastRow {
            ///     #[inline(always)]
            ///     pub fn new(a: u32, b: u64, c: u32) -> Self {
            ///         Self {
            ///             a: a.to_le(),
            ///             b: b.to_le(),
            ///             c: c.to_le()
            ///         }
            ///     }
            ///
            ///     #[inline(always)]
            ///     pub fn as_u32_ptr(&self) -> *const u32 {
            ///         let struct_pointer: *const Self = self;
            ///         struct_pointer as *const u32
            ///     }
            /// }
            ///
            /// let mut rng = ChaCha8Rng::from_seed([0u8; 32]);
            /// // maxing out state[12] makes it harder to
            /// // replicate with IETF variants, which many implementations use
            /// let last_row = LastRow::new(u32::MAX, 2, 3);
            /// unsafe {
            ///     rng.set_last_row(last_row.as_u32_ptr());
            /// }
            /// ```
            #[inline]
            pub unsafe fn set_last_row(&mut self, data: *const u32) {
                self.reset(0);
                unsafe {
                    core::ptr::copy_nonoverlapping(data, self.core.state.as_mut_ptr().add(12), 4)
                }
            }
        }
    };
}

impl_chacha_rng!(ChaCha8Rng, R8);
impl_chacha_rng!(ChaCha12Rng, R12);
impl_chacha_rng!(ChaCha20Rng, R20);

#[cfg(test)]
mod tests {
    use rand_core::{Rng, SeedableRng};

    use original_chacha::ChaCha8Rng as OracleRng;
    extern crate alloc;
    use alloc::alloc::{Layout, alloc, dealloc};

    use super::*;

    #[repr(C, packed(4))]
    struct LastRow {
        a: u32,
        b: u64,
        c: u32,
    }

    impl LastRow {
        #[inline(always)]
        pub fn new(a: u32, b: u64, c: u32) -> Self {
            Self {
                a: a.to_le(),
                b: b.to_le(),
                c: c.to_le(),
            }
        }

        #[inline(always)]
        pub fn as_u32_ptr(&self) -> *const u32 {
            let struct_pointer: *const Self = self;
            struct_pointer as *const u32
        }
    }

    #[test]
    fn set_last_row() {
        let mut rng_1 = ChaCha8Rng::from_seed([0u8; 32]);
        let mut rng_2 = ChaCha8Rng::from_seed([0u8; 32]);

        rng_1.set_stream(1);
        rng_1.set_block_pos(1);

        let last_row = LastRow::new(1, 1 << 32, 0);
        unsafe {
            rng_2.set_last_row(last_row.as_u32_ptr());
        }
        assert_eq!(rng_1.next_u32(), rng_2.next_u32());
    }

    #[test]
    fn rng_fill_bytes_tests() {
        let mut oracle = OracleRng::from_seed([0u8; 32]);
        let mut test_rng = ChaCha8Rng::from_seed([0u8; 32]);

        let mut arr = [0u8; 4096];
        let mut test = [0u8; 4096];

        for _ in 0..10 {
            for size in 1..4096 {
                let word_pos = oracle.get_word_pos();
                oracle.fill_bytes(&mut arr[0..size]);
                test_rng.fill_bytes(&mut test[0..size]);
                for byte in 0..size {
                    let word = word_pos + (byte as u128 / 4);
                    assert!(
                        arr[byte] == test[byte],
                        "Inequal byte at byte #{}, word #{}, state #{}, o = {} != {}, size = {}",
                        byte,
                        word,
                        word % 16,
                        arr[byte],
                        test[byte],
                        size
                    );
                }
            }
        }
    }

    #[test]
    fn aligned_fill_bytes() {
        let size = 4096;

        let layout = Layout::from_size_align(size, 16).unwrap();
        let ptr = unsafe { alloc(layout) };

        assert_eq!(ptr as usize & 0xF, 0);

        let test = unsafe { core::slice::from_raw_parts_mut(ptr, size) };

        let mut oracle = OracleRng::from_seed([0u8; 32]);
        let mut test_rng = ChaCha8Rng::from_seed([0u8; 32]);

        let mut arr = [0u8; 4096];

        for _ in 0..10 {
            for size in 1..4096 {
                let word_pos = oracle.get_word_pos();
                oracle.fill_bytes(&mut arr[0..size]);
                test_rng.fill_bytes(&mut test[0..size]);
                for byte in 0..size {
                    let word = word_pos + (byte as u128 / 4);
                    assert!(
                        arr[byte] == test[byte],
                        "Inequal byte at byte #{}, word #{}, state #{}, o = {} != {}, size = {}",
                        byte,
                        word,
                        word % 16,
                        arr[byte],
                        test[byte],
                        size
                    );
                }
            }
        }
        unsafe { dealloc(ptr, layout) };
    }

    #[test]
    fn next_u64_tests() {
        let mut rng = ChaCha8Rng::from_seed([0u8; 32]);
        for _ in 0..100 {
            assert_ne!(rng.next_u64(), 0);
        }
    }
}
